# Generated by Django 5.1.2 on 2024-11-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_classgroup_created_date_classgroup_deleted_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classgroup',
            table='class_group',
        ),
        migrations.AlterModelTable(
            name='departament',
            table='departament',
        ),
        migrations.AlterModelTable(
            name='period',
            table='period',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='schedule',
        ),
        migrations.AlterModelTable(
            name='schoolroom',
            table='school_room',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subject',
        ),
    ]
