# Generated by Django 5.1.2 on 2024-11-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_classgroup_table_alter_departament_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperiod',
            name='end_date',
            field=models.DateField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='historicalperiod',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='period',
            name='end_date',
            field=models.DateField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
    ]
