# Generated by Django 5.1.3 on 2024-11-24 05:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_course_unique_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_course',
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(condition=models.Q(('state', True)), fields=('teacher', 'group', 'subject', 'period'), name='unique_course'),
        ),
    ]
