# Generated by Django 5.1.2 on 2024-10-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_historicaluser_email_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='ADMIN', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='ADMIN', max_length=30),
        ),
    ]
