# Generated by Django 5.1.2 on 2024-11-05 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_studentprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalstudentprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Perfil de Estudiante', 'verbose_name_plural': 'historical Perfiles de Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='historicalteacherprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Perfil de Docente', 'verbose_name_plural': 'historical Perfiles de Docentes'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Perfil de Estudiante', 'verbose_name_plural': 'Perfiles de Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'verbose_name': 'Perfil de Docente', 'verbose_name_plural': 'Perfiles de Docentes'},
        ),
        migrations.AlterModelTable(
            name='studentprofile',
            table='student_profile',
        ),
        migrations.AlterModelTable(
            name='teacherprofile',
            table='teacher_profile',
        ),
    ]
