# Generated by Django 5.1.2 on 2024-11-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_historicalstudentprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='username',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nombre de Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre de Usuario'),
        ),
    ]
