# Generated by Django 5.1.2 on 2024-10-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendances',
            name='attendance_date',
            field=models.DateField(unique=True, verbose_name='Fecha de asistencia'),
        ),
    ]
