# Generated by Django 5.1.2 on 2024-10-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_alter_attendances_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendances',
            name='observation',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Observación'),
        ),
    ]
