# Generated by Django 5.1.3 on 2024-12-03 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0003_initial'),
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='groups.group', verbose_name='Grupo'),
        ),
    ]
