# Generated by Django 5.1.2 on 2024-10-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0003_alter_attendances_observation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendances',
            options={'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='enrollments',
            options={'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
    ]
