# Generated by Django 5.1.3 on 2024-12-03 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0004_alter_enrollment_group'),
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='groups.group', verbose_name='Grupo'),
        ),
    ]
