# Generated by Django 5.1.2 on 2024-11-05 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0005_rename_classgroup_enrollments_class_group_and_more'),
        ('groups', '0007_alter_classgroup_table_alter_departament_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendances',
            name='attendance_status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave')], default='PRESENT', max_length=20, verbose_name='Estado de asistencia'),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendances.enrollments', verbose_name='Inscripción'),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.classgroup', verbose_name='Grupo de clases'),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='historicalattendances',
            name='attendance_status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave')], default='PRESENT', max_length=20, verbose_name='Estado de asistencia'),
        ),
        migrations.AlterField(
            model_name='historicalattendances',
            name='enrollment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attendances.enrollments', verbose_name='Inscripción'),
        ),
        migrations.AlterField(
            model_name='historicalenrollments',
            name='class_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='groups.classgroup', verbose_name='Grupo de clases'),
        ),
        migrations.AlterField(
            model_name='historicalenrollments',
            name='student',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
    ]
