# Generated by Django 5.1.3 on 2024-12-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0005_alter_enrollment_group'),
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_attendance',
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('state', True)), fields=('enrollment', 'course', 'attendance_date', 'attendance_status'), name='unique_attendance'),
        ),
    ]
