# Generated by Django 5.1.3 on 2024-11-21 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0006_alter_attendances_attendance_status_and_more'),
        ('groups', '0009_remove_classgroup_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendances',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.course', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='historicalattendances',
            name='course',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='groups.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='Grupo de clases'),
        ),
        migrations.AlterField(
            model_name='historicalenrollments',
            name='class_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='groups.group', verbose_name='Grupo de clases'),
        ),
    ]
