# Generated by Django 5.1.3 on 2025-01-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0006_remove_attendance_unique_attendance_and_more'),
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_attendance',
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('state', True)), fields=('enrollment', 'course', 'attendance_date'), name='unique_attendance'),
        ),
    ]
