# Generated by Django 5.1.3 on 2024-11-22 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0007_attendances_course_historicalattendances_course_and_more'),
        ('groups', '0010_delete_classgroup_delete_historicalclassgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollments',
            name='class_group',
        ),
        migrations.RemoveField(
            model_name='historicalenrollments',
            name='class_group',
        ),
        migrations.AddField(
            model_name='enrollments',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='historicalenrollments',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='groups.group', verbose_name='Grupo'),
        ),
    ]
