# Generated by Django 5.1.3 on 2024-11-23 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0008_remove_enrollments_class_group_and_more'),
        ('groups', '0010_delete_classgroup_delete_historicalclassgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollments',
            constraint=models.UniqueConstraint(fields=('student', 'group'), name='unique_inscripcion'),
        ),
    ]
