# Generated by Django 5.1.3 on 2024-11-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0009_enrollments_unique_inscripcion'),
        ('groups', '0011_course_unique_course'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendances',
            constraint=models.UniqueConstraint(fields=('enrollment', 'course', 'attendance_date'), name='unique_attendance'),
        ),
    ]
