# Generated by Django 5.1.3 on 2024-11-24 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0010_attendances_unique_attendance'),
        ('groups', '0011_course_unique_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollments',
            name='unique_inscripcion',
        ),
        migrations.AddConstraint(
            model_name='enrollments',
            constraint=models.UniqueConstraint(condition=models.Q(('state', True)), fields=('student', 'group'), name='unique_inscripcion'),
        ),
    ]
