# Generated by Django 5.1.3 on 2024-11-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0011_remove_enrollments_unique_inscripcion_and_more'),
        ('groups', '0011_course_unique_course'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendances',
            name='unique_attendance',
        ),
        migrations.AddConstraint(
            model_name='attendances',
            constraint=models.UniqueConstraint(condition=models.Q(('state', True)), fields=('enrollment', 'course', 'attendance_date'), name='unique_attendance'),
        ),
    ]
